my_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_base_to_base
    - arm_joint_01
    - arm_joint_02
    - arm_joint_03
    - arm_joint_04
  gains:
    arm_base_to_base:
      p: 100
      d: 0.01
      i: 0
      i_clamp: 0
    arm_joint_01:
      p: 100
      d: 0.01
      i: 0
      i_clamp: 0
    arm_joint_02:
      p: 100
      d: 0.01
      i: 0
      i_clamp: 0
    arm_joint_03:
      p: 100
      d: 0.01
      i: 0
      i_clamp: 0
    arm_joint_04:
      p: 100
      d: 0.01
      i: 0
      i_clamp: 0
